### ISSUE TITLE
nuget?

### ISSUE THREAD

**Issue by Cheesebaron** [gshackles/FloatLabeledEntry#4]
I can haz plz?

**Comment by SourceHollandaise** [comment]
Nuget package is coming soon. I'm working currently on a Mac and so I can't build packages.

Next week I will provide it to nuget.

Meanwhile please download the sources.

Greetings, Jörg

**Comment by Cheesebaron** [comment]
Sweet. Want me to whip up a nuspec, or?

**Comment by SourceHollandaise** [comment]
:-) No, no problem I will build them soon. 

Unless you want to do it...

Which project do you mean TriggerSol or Trigger.Smart?

I'm a little bit confused today. Sorry.

**Comment by Cheesebaron** [comment]
You are looking at: gshackles/JVFloatSharp

**Comment by SourceHollandaise** [comment]
Oh so confused! Not my day. Sorry. 

I can try build it next week.

**Comment by gshackles** [comment]
Been on my TODO list for awhile, just haven't had a chance to do it. I was also planning on renaming the project which I'd probably do at the same time. Will try and prioritize this soon. In the meantime, it's just one C# file :smile:

**Comment by gshackles** [comment]
[Done! :grinning:](https://www.nuget.org/profiles/gshackles)
