### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by homerokzam** [gshackles/FloatLabeledEntry#5]
Do you have a similar component to Android?

**Comment by Cheesebaron** [comment]
Look here: https://github.com/Johan-dutoit/JVFloatSharp

**Comment by homerokzam** [comment]
Thank you!

**Comment by gshackles** [comment]
I had planned to add one to this repository, but there's no longer a need [as Google has shipped their own](http://developer.android.com/reference/android/support/design/widget/TextInputLayout.html?utm_campaign=io15&utm_source=dac&utm_medium=blog). I suggest using that.

**Comment by homerokzam** [comment]
I made the implementation on iOS for use in a Xamarin Forms project and it worked ok. I can not do the same on the Android project (with the library you refer me). You know how to solve this problem?

Thanks.
