### ISSUE TITLE
The Name parameter of the Registrar attribute on the class contains an invalid character: ' '

### ISSUE THREAD

**Issue by andrius-k** [gshackles/FloatLabeledEntry#6]
When building for actual device I get this warning:

_MyApp/iOS/MTOUCH: Warning MT4146: The Name parameter of the Registrar attribute on the class 'FloatLabeledEntry.FloatLabeledTextField' contains an invalid character: ' ' (0x20) (MT4146) (MyApp.iOS)_

And build fails with this error:

_MyApp/iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at http://bugzilla.xamarin.com (MT4109) (MyApp.iOS)_

It builds and runs fine when targeting simulator. 

It appears that changing Register attribute not to use spaces would solve the issue:
`[Register ("FloatLabeledTextField"), DesignTimeVisible (true)]`
`public class FloatLabeledTextField : UITextField`

**Comment by gshackles** [comment]
Crap, sorry about that! Must have gotten lost in some cleanup I was trying to do. I just published v1.1.1 that should take care of that for ya!

**Comment by andrius-k** [comment]
v1.1.1 indeed fixed the issue. Thanks for quick response ;)
